Add YINSH
lazarow/combinatorial-games-platform pull request #7
Opened 2023-12-02 20:10 UTC by PanHoracy

Implementation of YINSH game (https://boardgamegeek.com/boardgame/7854/yinsh):
* Added YINSH game
* Added game description
* Added authors

2023-12-04 12:25 UTC, lazarow requested changes
Akceptuję po poprawkach.

2023-12-04 12:25 UTC, lazarow commented on .gitignore
Niepotrzebnie tyle wpisów. Możecie zostawić `.idea`.

2023-12-05 16:26 UTC, PanHoracy commented
> Akceptuję po poprawkach.

Poprawki wprowadzone

2023-12-06 09:39 UTC, lazarow approved these changes

2023-12-06 09:39 UTC, merged